apiVersion: v1
kind: Service
metadata:
 name: platformnpservice-srv
spec:
 type: NodePort
 selector:
  app: platformservice # target depl service
 ports:
  - name: platformservice # array element
    protocol: TCP
    port: 80
    targetPort: 80